version: '3.4'

services:
  booksearch:
    image: ${DOCKER_REGISTRY-}booksearch
    build:
      context: .
      dockerfile: BookSearch/Dockerfile
    ports:
      - "9000:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - booksearchapi

  booksearchapi:
    image: ${DOCKER_REGISTRY-}booksearchapi
    build:
      context: .
      dockerfile: BookSearchAPI/Dockerfile
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: books
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local

